module.exports = {
  // YOTI
  ADD_QR_CODE: 'ADD_QR_CODE',
  SET_UP_FOR_MOBILE: 'SET_UP_FOR_MOBILE',
  // forms
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  NEXT_FORM: 'NEXT_FORM',
  ADD_CRITERIA: 'ADD_CRITERIA'
}
