module.exports = {
  // YOTI
  ADD_QR_CODE: 'ADD_QR_CODE',
  CLOSE_QR: 'CLOSE_QR',
  OPEN_QR: 'OPEN_QR',
  SET_UP_FOR_MOBILE: 'SET_UP_FOR_MOBILE',
  // forms
  CHANGE_MODAL: 'CHANGE_MODAL',
  CHANGE_FORM: 'CHANGE_FORM',
  SHOW_URL_REQUIRED_MESSAGE: 'SHOW_URL_REQUIRED_MESSAGE',
  SHOW_CRITERIA_REQUIRED_MESSAGE: 'SHOW_CRITERIA_REQUIRED_MESSAGE',
  VALID_EMAIL_REQUIRED_MESSAGE: 'VALID_EMAIL_REQUIRED_MESSAGE',
  HIDE_VALID_EMAIL_REQUIRED_MESSAGE: 'HIDE_VALID_EMAIL_REQUIRED_MESSAGE',
  TOGGLE_CRITERIA: 'TOGGLE_CRITERIA',
  SAVE_URL: 'SAVE_URL',
  SAVE_DESCRIPTION: 'SAVE_DESCRIPTION',
  SAVE_EMAIL: 'SAVE_EMAIL'
}
