module.exports = {
  // YOTI
  ADD_QR_CODE: 'ADD_QR_CODE',
  CHANGE_QR: 'CHANGE_QR',
  SET_UP_FOR_MOBILE: 'SET_UP_FOR_MOBILE',
  // forms
  CHANGE_MODAL: 'CHANGE_MODAL',
  CHANGE_FORM: 'CHANGE_FORM',
  TOGGLE_CRITERIA: 'TOGGLE_CRITERIA',
  SAVE_URL: 'SAVE_URL',
  SAVE_DESCRIPTION: 'SAVE_DESCRIPTION'
}
